
const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export default {
  LOGIN_USER_REQUEST,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
}
