const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
const CREATE_USER_ERROR = "CREATE_USER_ERROR"

export default {
  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_ERROR,
}
